name: Build


on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'
    

jobs:

  name: build GuidoLib
    runs-on: ubuntu-latest

    build:
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/GuidoLib
      - name: Build
        run: dotnet build  ./src/GuidoLib --no-restore
      - name: Test
        run: dotnet test  ./src/GuidoLib --no-build --verbosity normal
